### ISSUE TITLE
Same AOC assigned to same user multiple times

### ISSUE THREAD

**Issue by SilasBerger** [wozuo/thingy-api#1]
I executed the `POST` request `https://wicked-pumpkin-99140.herokuapp.com/users/81/clothes/4` with body 
`{
"fromTemp": 0,
"toTemp": 15
}`
twice, to see what the API does in that case. 

The first time it worked as expected, and the second time, it returned 404. However, the associtation was still created a second time, shown by the result of `GET` to `https://wicked-pumpkin-99140.herokuapp.com/users/81/clothes`. 

Also, the `DELETE` request to `https://wicked-pumpkin-99140.herokuapp.com/users/81/clothes/4` now returns 404 and doesn't delete the association.

**Comment by wozuo** [comment]
You're right, thanks for bringing this to my attention. This problem should now be fixed. The API will now return `409 Conflict` if an article of clothing is already assigned to a user.
